### ISSUE TITLE
Panic in char index

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/annotate-snippets-rs#136]
While working on https://github.com/rust-lang/rust-clippy/pull/11421, I encountered this error:

```
thread 'main' panicked at /home/imperio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/annotate-snippets-0.11.4/src/renderer/display_list.rs:1103:29:
byte index 18 is not a char boundary; it is inside '脑' (bytes 16..19) of `    let _ = "电脑\0".as_ptr();`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

with this code:

```rust
fn main() {
    let _ = "电脑\0".as_ptr();
    //~^ clippy::manual_c_str_literals
}
```

I would have loved to send a fix but I couldn't figure out how to add a test. ^^'

**Comment by oli-obk** [comment]
I had seen some ui test issues like that but I thought I fixed them once and for all. Maybe the fix isn't published and used in clippy yet

**Comment by oli-obk** [comment]
definitely not annotate-snippets' fault, so closing
