### ISSUE TITLE
char boundary panic on 0.11.4, fixed on master

### ISSUE THREAD

**Issue by lvaroqui** [rust-lang/annotate-snippets-rs#161]
Hello, 

I'm using [typst-languagetool](https://github.com/antonWetzel/typst-languagetool), which relies on `annotate-snippets`, and faced a panic on bad char slicing of UTF-8 string in annotate-snippets. Here's what the error looks like (I redacted string for privacy and clarity):

```
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/annotate-snippets-0.11.4/src/renderer/display_list.rs:369:29:
byte index 132 is not a char boundary; it is inside 'à' (bytes 131..133) of `<...> à chaq`
```

After a little digging, I found out that the issue was resolved back in June by [this commit](https://github.com/rust-lang/annotate-snippets-rs/commit/9ec2939584d9d4ad6c601020d5c68ca08bfceb66).

Is there a plan to release a new version of this crate to make this bug fix available?

Thanks!

**Comment by Muscraft** [comment]
Whoops, sorry, I missed releasing that. 

I just released [`0.11.5`](https://crates.io/crates/annotate-snippets/0.11.5), which includes that fix.
