### ISSUE TITLE
Fixtures test: `serde_yaml` not implement zero copy deserializer

### ISSUE THREAD

**Issue by zzau13** [rust-lang/annotate-snippets-rs#31]
Can I change `yaml` for `toml` because yaml [not implement zero copy deserializer]( https://github.com/dtolnay/serde-yaml/blob/master/src/de.rs#L1007), while [toml does implement it](https://github.com/alexcrichton/toml-rs/blob/master/src/de.rs#L75-L83)? 

I need it because I'm fixing the copy at `Snippet` to `DisplayList` cast

**Comment by botika** [comment]
It's for testing, if you don't implement `serde::Deserializer` can not get lifetime to `Snippet`.

**Comment by zbraniecki** [comment]
hmm, yeah, I don't think it'll be an issue. Feel free to switch!

**Comment by botika** [comment]
It is not an issue, just a question. I didn't know any other way to talk with you :smile: , I close it
