### ISSUE TITLE
Decouple `FormatOptions` from `Snippet`

### ISSUE THREAD

**Issue by epage** [rust-lang/annotate-snippets-rs#40]
At the layer I want to be creating `Snippet`s, I won't know whether colored formatting is appropriate or not.  That seems like a concern for when converting into a `DisplayList`.

**Comment by epage** [comment]
I can work around this by mutating the fields but in general, it doesn't seem to be  separating concerns appropriately.

**Comment by zbraniecki** [comment]
The way you construct the `Snippet` is flexible, and all that matters is that in the end you pass the right data to building Display List.

Maybe what you're reporting here is that `FormatOptions` are not a property of `Snippet` and instead should be separate and passed together into `DisplayList` builder?

**Comment by epage** [comment]
> Maybe what you're reporting here is that FormatOptions are not a property of Snippet and instead should be separate and passed together into DisplayList builder?

Yes, separating styling from semantic information.

**Comment by epage** [comment]
Closed via #67
