### ISSUE TITLE
Switch CI from travis to GH actions

### ISSUE THREAD

**Issue by zbraniecki** [rust-lang/annotate-snippets-rs#48]
Travis is falling apart, we need to switch to GH actions.

**Comment by jim4067** [comment]
I would like to help out with this. I made a simple github workflow that runs clippy and tests on PR #49

**Comment by zbraniecki** [comment]
That works great, thank you!

Can you also add `cargo fmt` and remove Travis?

**Comment by zbraniecki** [comment]
aaand update badge? :)

**Comment by jim4067** [comment]
Okay. i'll get down to it 👍🏾

**Comment by jim4067** [comment]
About removing travis-ci, what about, code coverage  by coveralls  and adding a PR actions workflow?

**Comment by zbraniecki** [comment]
> About removing travis-ci, what about, code coverage by coveralls and adding a PR actions workflow?

yup!
