### ISSUE TITLE
Source annotate ranges should use bytes not chars

### ISSUE THREAD

**Issue by Muscraft** [rust-lang/annotate-snippets-rs#77]
Currently, `SourceAnnotation`'s `range` field is based on chars, not bytes. This can be a little confusing for users and can cause issues when dealing with spans from things like `toml` errors. It would make more sense to have users give us bytes, and we calculate the char spans internally. This would make the API easier to use as most people can handle going to bytes, but going from bytes -> chars can be very hard.

**Comment by epage** [comment]
For me, there are two aspects to this
- `annotate-snippets` is responsible for rendering so it shouldn't accept a rendering-focused unit but handle that behind the scenes
- Turning bytes into column counts is complicated and we likely don't want everyone re-implementing it incorrectly, in different ways
