### ISSUE TITLE
Strip code to the left and right in diagnostics for long lines

### ISSUE THREAD

**Issue by phansch** [rust-lang/annotate-snippets-rs#8]
Analog to https://github.com/rust-lang/rust/pull/63402

My initial idea is to hook this up here, where we would call into some other place that does the margin calculation:

https://github.com/rust-lang/annotate-snippets-rs/blob/11835686622c9bf1d8a22263acb80943b783324b/src/formatter/mod.rs#L185

But I guess we'll also have to update the `range` of `DisplaySourceLine::Annotation`, so maybe it should happen earlier?

**Comment by oli-obk** [comment]
As a first step, one could move the rustc-independent code from https://github.com/rust-lang/rust/pull/63402 to `annotate-snippets` and make rustc use it. This way we don't duplicate code.

**Comment by botika** [comment]
@phansch  The only thing I do not know how to transfer to the library is [`annotated_file.multiline_depth`](https://github.com/rust-lang/rust/blob/master/src/librustc_errors/emitter.rs#L1408-L1412). 
I don't know exactly what it's for, I just see that it reduces the size of the column. I don't know exactly what it's for, I just see that it reduces the size of the column. At the moment I have adapted the margin and put an entry for `FormatOptions {strip_code_line: Option <usize>, ..}`
I will do the PR without treating this variable.
